version: "3"

services:
  main:
    container_name: main
    build: ./app
    ports:
      - "5000:5000"
    links:
      - rabbitmq
      - redis
    depends_on:
        rabbitmq:
          condition: service_healthy

    environment:
      - FLASK_ENV=development
    volumes:
      - ./app:/app

  rabbitmq:
    container_name: rabbitmq
    image: bitnami/rabbitmq:3.8.27
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 30s
      retries: 3
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    

  worker:
    build:
      context: ./worker
    hostname: worker
    entrypoint: celery
    command: -A tasks worker --loglevel=info
    volumes:
      - ./worker:/app
    depends_on:
        rabbitmq:
          condition: service_healthy

      # https://hackmd.io/@samueltseng/Flask-Celery-DockerCompose


  flower:
    image: mher/flower:0.9.7
    environment:
      - CELERY_BROKER_URL=amqp://user:bitnami@rabbitmq
      - FLOWER_PORT=8888
    ports:
      - 8889:8888
    depends_on:
        rabbitmq:
          condition: service_healthy

# https://medium.com/@tanchinhiong/separating-celery-application-and-worker-in-docker-containers-f70fedb1ba6d